[package]
name = "agent"
version = "0.1.0"
edition = "2024"

[dependencies]
async-openai = "0.29.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
schemars = "0.8"
thiserror = "2.0.16"
async-trait = "0.1.89"
tokio = "1.47.1"
